// Sample dataset — mirrors real CLI output structure from scorer.py + report.py
window.FS_TICKERS = [
  {
    ticker: "JPM", name: "JP Morgan Chase & Co",
    sector: "Financial Services", industry: "Banks—Diversified",
    classification: "UNDERVALUED", confidence: "medium",
    price: 198.45, change: 2.31, changePct: 1.18, mcap: "572B",
    metrics: {
      forward_pe: 10.2, ev_ebitda: null, fcf_yield: 0.081,
      roe: 0.152, debt_equity: null, cf_quality: 1.1,
      revenue_growth: 0.04, beta: 1.05,
    },
    bench: { pe: 13.0, ev_ebitda: null },
    range52: { low: 167.20, high: 215.80, ma50: 192.30, ma200: 188.50 },
    flags: [
      { kind: "u", text: "Trading at a discount to sector on 2/3 valuation metrics" },
      { kind: "u", text: "Quality filters pass: ROE 15.2% · CF Quality 1.1x (earnings backed by cash)" },
    ],
    sectorNote: "Banks operate at 8–20x leverage by design; D/E threshold does not apply. EV/EBITDA suppressed.",
    suppressed: ["ev_ebitda"], deThreshold: null,
  },
  {
    ticker: "AAPL", name: "Apple Inc.",
    sector: "Technology", industry: "Consumer Electronics",
    classification: "QUALITY_PREMIUM", confidence: "medium",
    price: 272.11, change: -1.84, changePct: -0.67, mcap: "4.1T",
    metrics: {
      forward_pe: 29.0, ev_ebitda: 26.4, fcf_yield: 0.027,
      roe: 1.52, debt_equity: 1.0, cf_quality: 1.25,
      revenue_growth: 0.02, beta: 1.22,
    },
    bench: { pe: 20.0, ev_ebitda: 4.0 },
    range52: { low: 221.10, high: 298.40, ma50: 268.10, ma200: 251.50 },
    flags: [
      { kind: "p", text: "Trading at a premium to sector on 3/3 valuation metrics" },
      { kind: "p", text: "Quality is strong: ROE 152.0% — market may be pricing in growth" },
    ],
    sectorNote: "Tech companies often trade at high P/E; focus on PEG and EV/Revenue for growth names.",
    suppressed: ["price_to_book"],
  },
  {
    ticker: "INTC", name: "Intel Corporation",
    sector: "Technology", industry: "Semiconductors",
    classification: "VALUE_TRAP", confidence: "medium",
    price: 67.26, change: 0.15, changePct: 0.22, mcap: "290B",
    metrics: {
      forward_pe: 60.2, ev_ebitda: 27.5, fcf_yield: -0.013,
      roe: 0.00, debt_equity: 0.4, cf_quality: -36.3,
      revenue_growth: -0.08, beta: 1.18,
    },
    bench: { pe: 37.0, ev_ebitda: 26.0 },
    range52: { low: 18.50, high: 72.10, ma50: 62.40, ma200: 48.90 },
    flags: [
      { kind: "t", text: "Looks cheap on multiple metrics — but quality concerns:" },
      { kind: "t", text: "WARNING: ROE is 0.0% (below 10% threshold)", caps: "WARNING:" },
      { kind: "t", text: "WARNING: CF Quality is -36.3x — earnings not backed by cash", caps: "WARNING:" },
      { kind: "o", text: "REVENUE DECLINE: -8.0% YoY — investigate if structural", caps: "REVENUE DECLINE:" },
      { kind: "o", text: "NEAR 52-WEEK HIGH: trading in top 10% of range", caps: "NEAR 52-WEEK HIGH:" },
    ],
    sectorNote: "Tech companies often trade at high P/E; focus on PEG and EV/Revenue for growth names.",
    suppressed: ["price_to_book"],
  },
  {
    ticker: "XOM", name: "Exxon Mobil Corporation",
    sector: "Energy", industry: "Oil & Gas Integrated",
    classification: "QUALITY_PREMIUM", confidence: "medium",
    price: 149.94, change: 1.02, changePct: 0.68, mcap: "668B",
    metrics: {
      forward_pe: 14.9, ev_ebitda: 11.3, fcf_yield: 0.020,
      roe: 0.111, debt_equity: 0.2, cf_quality: 1.4,
      revenue_growth: 0.01, beta: 0.88,
    },
    bench: { pe: 22.0, ev_ebitda: 8.0 },
    range52: { low: 102.10, high: 158.90, ma50: 145.20, ma200: 128.70 },
    flags: [
      { kind: "p", text: "Trading at a premium to sector on 2/3 valuation metrics" },
      { kind: "p", text: "Quality is strong: ROE 11.1% — market may be pricing in growth" },
      { kind: "t", text: "CYCLICAL SECTOR: P/E unreliable at earnings peaks/troughs. EV/EBITDA weighted more heavily.", caps: "CYCLICAL SECTOR:" },
    ],
    sectorNote: "Cyclical sector: P/E unreliable at earnings peaks/troughs. EV/EBITDA weighted more heavily.",
  },
  {
    ticker: "TSLA", name: "Tesla, Inc.",
    sector: "Consumer Cyclical", industry: "Auto Manufacturers",
    classification: "OVERVALUED", confidence: "high",
    price: 421.88, change: -8.14, changePct: -1.89, mcap: "1.3T",
    metrics: {
      forward_pe: 82.4, ev_ebitda: 68.2, fcf_yield: 0.008,
      roe: 0.219, debt_equity: 0.3, cf_quality: 0.91,
      revenue_growth: 0.02, beta: 2.11,
    },
    bench: { pe: 20.0, ev_ebitda: 13.0 },
    range52: { low: 205.30, high: 488.50, ma50: 438.10, ma200: 358.40 },
    flags: [
      { kind: "o", text: "Expensive on 3/3 valuation metrics with no clear quality offset" },
      { kind: "o", text: "NEAR 52-WEEK HIGH: trading in top 10% of range", caps: "NEAR 52-WEEK HIGH:" },
    ],
  },
  {
    ticker: "MSFT", name: "Microsoft Corporation",
    sector: "Technology", industry: "Software—Infrastructure",
    classification: "FAIR_VALUE", confidence: "low",
    price: 484.22, change: 3.41, changePct: 0.71, mcap: "3.6T",
    metrics: {
      forward_pe: 22.0, ev_ebitda: 18.5, fcf_yield: 0.017,
      roe: 0.344, debt_equity: 0.3, cf_quality: 1.18,
      revenue_growth: 0.16, beta: 0.92,
    },
    bench: { pe: 34.0, ev_ebitda: 18.0 },
    range52: { low: 385.60, high: 512.40, ma50: 478.20, ma200: 445.10 },
    flags: [
      { kind: "p", text: "No strong valuation divergence — trading near sector norms" },
    ],
  },
  {
    ticker: "GOOGL", name: "Alphabet Inc.",
    sector: "Communication Services", industry: "Internet Content & Information",
    classification: "UNDERVALUED", confidence: "high",
    price: 178.34, change: 2.05, changePct: 1.16, mcap: "2.2T",
    metrics: {
      forward_pe: 18.2, ev_ebitda: 14.1, fcf_yield: 0.049,
      roe: 0.301, debt_equity: 0.1, cf_quality: 1.22,
      revenue_growth: 0.13, beta: 1.04,
    },
    bench: { pe: 24.0, ev_ebitda: 18.0 },
    range52: { low: 148.10, high: 205.60, ma50: 184.30, ma200: 172.90 },
    flags: [
      { kind: "u", text: "Trading at a discount to sector on 3/3 valuation metrics" },
      { kind: "u", text: "Quality filters pass: ROE 30.1% · CF Quality 1.2x" },
    ],
  },
  {
    ticker: "T", name: "AT&T Inc.",
    sector: "Communication Services", industry: "Telecom Services",
    classification: "VALUE_TRAP", confidence: "medium",
    price: 22.45, change: -0.18, changePct: -0.80, mcap: "161B",
    metrics: {
      forward_pe: 8.1, ev_ebitda: 6.2, fcf_yield: 0.113,
      roe: 0.08, debt_equity: 1.4, cf_quality: 0.62,
      revenue_growth: -0.012, beta: 0.62,
    },
    bench: { pe: 17.0, ev_ebitda: 11.0 },
    range52: { low: 17.20, high: 24.10, ma50: 22.80, ma200: 21.10 },
    flags: [
      { kind: "t", text: "Looks cheap on 3/3 valuation metrics — but quality concerns:" },
      { kind: "t", text: "WARNING: ROE is 8.0% (below 10% threshold)", caps: "WARNING:" },
      { kind: "t", text: "WARNING: CF Quality is 0.6x — earnings may not be backed by cash", caps: "WARNING:" },
      { kind: "t", text: "Cheap for a reason? Investigate before buying." },
    ],
  },
  {
    ticker: "JNJ", name: "Johnson & Johnson",
    sector: "Healthcare", industry: "Drug Manufacturers—General",
    classification: "FAIR_VALUE", confidence: "low",
    price: 158.72, change: 0.41, changePct: 0.26, mcap: "382B",
    metrics: {
      forward_pe: 16.4, ev_ebitda: 13.2, fcf_yield: 0.054,
      roe: 0.192, debt_equity: 0.5, cf_quality: 1.08,
      revenue_growth: 0.04, beta: 0.54,
    },
    bench: { pe: 18.0, ev_ebitda: 14.0 },
    range52: { low: 142.30, high: 168.40, ma50: 156.80, ma200: 153.40 },
    flags: [{ kind: "p", text: "No strong valuation divergence — trading near sector norms" }],
  },
];
